services:

  # ── Angular SSR ─────────────────────────────────────────────────────────────
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: projeto-angular
    ports:
      - "4200:4000"          # acesse em http://localhost:4200
    environment:
      PORT: "4000"
      NODE_ENV: production
    restart: unless-stopped

